### ISSUE TITLE
crash on Samsung Note 10 plus with IC-7100

### ISSUE THREAD

**Issue by danielweatherly** [N0BOY/FT8CN#10]
The application crashes often at start of transmit. Seams stable in recieve. The crash is not consistant, but is often and only when going into transmit. 
Do you have a way to submit the debug dumpstate without posting it here? or can you tell me how to send only the part of the log you need, or specifics on what to send if different than the debug dumpstate?

**Comment by N0BOY** [comment]
Please try to see if the latest release works better. 

If not, you can send the crash report to NOBOY@arrl.net, I will forward it to the developer.
