### ISSUE TITLE
0.86

### ISSUE THREAD

**Issue by UT8IIV** [N0BOY/FT8CN#11]
Hello, there is no APK file in version 0.86, I really want to have the ability to save received callsigns in the program for radio observers. SWL. Thank you, regards.73!

**Comment by PD5DJ** [comment]
https://github.com/N0BOY/FT8CN/releases/download/v0%2C86/FT8CN_0.86_20230206.apk

**Comment by N0BOY** [comment]
Thanks for reporting the problem. The apk file has beed fixed in 0.86 release. 

SWL support is already on the roadmap, but pending for development. Currently expect to include SWL in release 0.88, or later.
