### ISSUE TITLE
(tr) uSDX Setup

### ISSUE THREAD

**Issue by Luca6605** [N0BOY/FT8CN#117]
Hello and thank you for the work done so far. Hi installed the new version 0.92 but I didn't notice any advantages for my rtx. In fact, I couldn't connect anyone. Are there any particular setups to do?

**Comment by d3m3vilurr** [comment]
if you want to connect with digital method(only 1 usb cable; without any audio cables), you have to use beta firmware.

https://dl2man.de/wp-content/uploads/2022/01/wp.php/beta.html

then select `(tr)uSDX (audio over cat)` in ft8cn

old (tr)uSDX firmware (<= 2.00t) doesn't support audio over CAT feature.
in this case, you have to select `(tr)uSDX (TS-480)` and also have to connect audio cables.

https://www.youtube.com/watch?v=W5M2C7rW0b0 this video is explain what you need for old firmware (DL2MAN explain it with wsjt-x but it would be pretty same in ft8cn)

**Comment by Luca6605** [comment]
Thanks for the info. I will update
