### ISSUE TITLE
Very few decodes

### ISSUE THREAD

**Issue by toddmazierski** [N0BOY/FT8CN#20]
Hello, and thank you for this app.

When using WSJT-X on my laptop, I get 10-20 decodes per cycle. When using FT8CN, I get 0-2. A few details:

* I've confirmed that my clock is synchronized
* I've tried FT8CN versions 0.83 and 0.86
* I'm using a Xiegu G90
* the "DeNoise" feature doesn't help

Is there a "Decode" depth setting (Fast/Normal/Deep) that could be increased, like in WSJT-X? Please let me know if there are other details I can provide.

<img width="400" alt="Screenshot of waterfall view with no FT8 decodes" src="https://user-images.githubusercontent.com/544541/226210723-79a7860a-6111-42b0-8223-00b74330ea27.png"/>
<img width="400" alt="Screenshot of waterfall view with no FT8 decodes" src="https://user-images.githubusercontent.com/544541/226210722-5bc625eb-4edd-4961-b6d2-a7650f88e404.png"/>
<img width="400" alt="Screenshot demonstrating synchronized clock" src="https://user-images.githubusercontent.com/544541/226210721-c8f2eb3d-ee8f-45a8-a5af-2a648db4035e.png"/>

**Comment by N0BOY** [comment]
Try increasing the sound-out/volume level on your phone?
