### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by nimanim** [N0BOY/FT8CN#27]
Please release for **IOS** , Because there is no suitable software on **IOS** for **FT8**.
73, EP7NIM

**Comment by Bu2ae** [comment]
Please release for YAESU FT-100(D) , Because there is no suitable model number for FT-100 rig in the FT8CN. Thanks！

73
BU2AE

**Comment by bg7yoz** [comment]
暂时还没有开发IOS版本的计划。
