### ISSUE TITLE
(tr)uSDX support?

### ISSUE THREAD

**Issue by alexjh** [N0BOY/FT8CN#29]
Hello, thank you for an amazing piece of software.

I've got a trusdx that I'm trying to get working, and I wonder if a setting can be added to control the DTR/RTS serial port lines - for trusdx they should be:

* DTR: high
* RTS: low

See this video from the creator of trusdx for context:
https://www.youtube.com/watch?v=W5M2C7rW0b0&t=174s

**Comment by bg7yoz** [comment]
(tr)uSDX的命令集兼容Kenwood TS-480或TS-450。
您可以试试在FT8CN中选择Kenwood TS-480。
波特率：38400。
控制模式：CAT。
不要选择DTR或RTS。

祝好运！

**Comment by alexjh** [comment]
It was an issue with my radio causing reboots when the USB cable is connected. I upgraded the firmware to 2.00t. This is a beta version, and needs a baud rate of 115200. After changing those settings, it's working in CAT mode.

这太棒了，谢谢！
