### ISSUE TITLE
*

### ISSUE THREAD

**Issue by UT8IIV** [N0BOY/FT8CN#3]
Hello, tell me, is it possible in the program to save the log in the adi format in the receive mode? or somehow save a log for radio surveillance without a PC?

**Comment by N0BOY** [comment]
This feature has been schedule in later release.

Thanks for your feedback.

**Comment by UT8IIV** [comment]
Здравствуйте 👋 спасибо за ответ! Буду ждать с нетерпением 👍📻😋73!!!

**Comment by UT8IIV** [comment]
👋 Thank you for your reply Hello! I will wait with resistance 👍📻😋73!!!
