### ISSUE TITLE
No rig control with Yaesu FT-991A

### ISSUE THREAD

**Issue by ilyxa** [N0BOY/FT8CN#32]
Rig: Yaesu FT-991A
Cable: few different USB-OTG cables, few different USB cables
Phone: Samsung A51 / UI5.1 (testing with Samsung S21FE), change UI lang w/ no results
Problem: no rig control / no TX
Freq not set, no transmission possible. Rig was set to its default values (MENU reset), already tried different speed, port, etc.

WSJT-X working just fine. All permission for app was done.

If I set freq - no changes, but if I then disconnect cable = rig change freq. It seems stuck somewhere somehow in transit (???).

Step to reproduce:
- connect phone
- start FT8CN (automatically or manually)
- make correct port selection
- set Freq (eg start TX) - no changes on rig
- disconnect rig = freq changed momentary after cable disconnection

Any ideas?

UB6LUM
73!

**Comment by bg7yoz** [comment]
hi, UB6LUM !

You need to make the following settings:

1.audio, Need to increase the value of DT GAIN.
2.CAT, set  CAT RTS = Off

good luck!
bg7yoz

**Comment by ilyxa** [comment]
> 2.CAT, set CAT RTS = Off

Nice! Thank you!

PS: https://televideo.ws/images/docs/FT-991A/FT991_2_Modi_Digitali.pdf good setup in in one place.
