### ISSUE TITLE
Serial port recognition

### ISSUE THREAD

**Issue by ua1arn** [N0BOY/FT8CN#4]
Hello.
Can you ignore vid/pid of serial port adapter?
For example, my TRX compound usb device appear as VID=0xFFFF and various PID in depend of configurations, CDC ACM port appear...
Then I change vid/pid to 0x0483/0x5732 - Kenwood TS-590S CAT work as expected...
![image](https://user-images.githubusercontent.com/34999007/208977977-1845a497-58b3-4b09-9221-61d2ba901cf8.png)

**Comment by N0BOY** [comment]
It's hard to accommodate every series chip.

Dev cannot support this request as the time.

**Comment by ua1arn** [comment]
I am not about every series chip.
I am about USB class 02 subclads 02 - CDC ACM device - significant set of modern home-made transcievers use this USB class for provide CAT control channel. Mentioned 0x0483/0x5732 also provide this interface.
