### ISSUE TITLE
I can't download the contacts.

### ISSUE THREAD

**Issue by Vhisy** [N0BOY/FT8CN#40]
Since i updated to the latest version i can't download the contacts.  I am connected to the same network.  and with previous versions I didn't have this problem.  Does anyone else have the same problem?

**Comment by UT8IIV** [comment]
Hello, please check again, network numbers sometimes change, all the best to you 👍

**Comment by Vhisy** [comment]
hello, the problem that this one had was that the APP was executed 2 times and there was a problem with the LOCAL IPs.  Closing a session from the APP fixed the problem.  Thanks for your answer.El 13 may 2023 7:26, Evgeniy ***@***.***> escribió:
Hello, please check again, network numbers sometimes change, all the best to you 👍
