### ISSUE TITLE
help solve the problem

### ISSUE THREAD

**Issue by UT8IIV** [N0BOY/FT8CN#41]
Hello, I work in reception mode SWL(US-I-777) .Please help me to deal with the problem, I'm uploading the log to eqsl  and this error is displayed, please help with advice,My QTH КN 78 😋😓73!📻

**Comment by UT8IIV** [comment]
![IMG_20230512_195655](https://github.com/N0BOY/FT8CN/assets/120315399/2f0fb3d5-414e-4ace-aaaf-42e41e770119)

**Comment by bg7yoz** [comment]
能否更详细描述一下您的问题？

**Comment by bg7yoz** [comment]
SWL日志中的网格，是呼叫的双方网格，不是您的网格，也不是您的QTH。

**Comment by UT8IIV** [comment]
> 

hello, thanks for the answer, the question is closed.73!👍👋
