### ISSUE TITLE
2 second time window is to short

### ISSUE THREAD

**Issue by RonMar26** [N0BOY/FT8CN#43]
Is it possible to make the time window a little bit longer.  It never happens that I have enough time to react in 2 seconds. Transmitting is always starting in the next time window, 30 seconds later. 

73 Ron
PD7RON

**Comment by bg7yoz** [comment]
FT8有效信号的传输时间是12.64秒，在15秒的时钟周期内，时间窗口是2.36秒，如果不包括前面的7个同步符号：7 * 0.16=1.12秒，最大的时间窗口应该是3.48秒，如果超出最大的时间窗口，能够解码的概率非常低了。

FT8CN的设定是在解码后的2.5秒内，在消息列表中向左滑动，可以在本周期内立即呼叫，如果超过2.5秒，将在下发射周期启动呼叫。设定为2.5秒的原因，是解码需要时间、电台开启ptt也需要时间。

其实，jtdx和wsjt中超出时间窗口发射是没有意义的，因为对方是没办法解码的，只是让用户使用的感受好一些而已。

**Comment by RonMar26** [comment]
Thanks for your answer. It is now clear to me how I have to answer. I did it by holding my finger on the call and than chose call. That takes a to long time.
Now I understand that you have to swipe to the left. Than it is faster and it is working when the decode time is fast enough
73 Ron
PD7RON
