### ISSUE TITLE
The call window remains empty

### ISSUE THREAD

**Issue by melagrano** [N0BOY/FT8CN#44]
Hi everybody,
I have installed FT8CN ver 0.88 patch 2 on my Samsung Galaxi note 8 . So to understand how the program works I used it only in reception using the micro of the smartphone. Honestly, the program demodulates the callsigns well, but if I click on a call that is making a call, the call window at the bottom of the smartphone screen remains empty. Only a few times the command is executed and the callsign I have chosen appears in the window at the bottom of the screen. I didn't understand if to do this test is necessary to connect the radio and I would like some of you to give me some information about it.
I thank you in advance for the answer.
Vincenzo i8bvw

**Comment by bg7yoz** [comment]
关于ft8cn的使用方法，您可以到YouTube中搜索"FT8CN"，您会看到很多介绍如何使用FT8CN的视频。

**Comment by melagrano** [comment]
谢谢你的信息。  de i8bvw

Il Sab 27 Mag 2023, 16:37 bg7yoz ***@***.***> ha scritto:
