### ISSUE TITLE
A little improvement suggestion

### ISSUE THREAD

**Issue by LYZhelloworld** [N0BOY/FT8CN#45]
Hi! First of all, thank you for making such a great app. I have used it for several months and there are some small issues that may be able to be fixed in future:

1. When the sender and the receiver have the same grid, or the receiver's grid is unknown, the comment shows `Distance: , QSO by FT8CN`. Maybe it is possible to hide the `Distance` field and only show `QSO by FT8CN` here in this case.
2. When downloading the QSO records, if the phone is not connected to a Wi-Fi, it shows `http://null:7050` as the URL. Is it better to replace it with some prompt like "Please connect to a valid Wi-Fi" or something else?
3. When uploading ADIF file to the app, some log software will ignore the `rst_rcvd` & `rst_sent` field if it is 0 (0dB). In that case, FT8CN will show `-120dB` for this missing field. This only happens when importing a log. Is it better to change the default value to 0?

Hope these suggestions will help improve the software.

**Comment by bg7yoz** [comment]
谢谢您的建议，计划在下一个版本中改进。
73

**Comment by N0BOY** [comment]
The release of v0.89 covers all your feedback. Thanks for your suggestion.
