### ISSUE TITLE
Audio output is attenuated after first transmission

### ISSUE THREAD

**Issue by gnotu** [N0BOY/FT8CN#68]
Some of us on the QRPLabs forum have noticed that a problem recently appeared when using FT8CN 0.89 with QRPLabs QMX transceivers.
(See https://groups.io/g/QRPLabs/topic/100738548)
At least two of us are running FT8CN on Google Pixel 6A Android phones.
We see that the first FT8 transmission happens normally.
But after that every subsequent transmission has no or little audio.
This continues until exiting FT8CN.
After re-running FT8CN, the first transmission is normal again and every transmission after that has low/no audio.
This seems to have started happening pretty recently so it may be due to an Android update.
I am willing to help troubleshoot it on my phone if you are unable to reproduce it.
Thank you and 73.

--Mike

**Comment by N0BOY** [comment]
Mike, was everything running smoothly on v0.88?

Let's try the following to troubleshoot the problem. 

Try to run FT8CN using the same phone/tablet but with different radios, or same radio with different Android device.

**Comment by bg7yoz** [comment]
hi, Mike

我们排除问题需要确认如下事情：

1.是不是Google Pixel 6A的问题？您可以换一个其它型号的手机，使用ft8cn 0.89和QRPLabs QMX测试，看看其它型号的手机是不是也有同样的问题。

2.是不是ft8cn 0.89的问题？您可以在Google Pixel 6A手机上，使用ft8cn 0.88 或 0.90测试，看看是不是也有同样的问题。注意：使用0.9版本前，要备份日志数据，因为0.9的数据库版本升级了，不能回退到旧版ft8cn。

3.是不是QRPLabs QMX transceiver的问题？使用Google Pixel 6A和ft8cn 0.89，测试其它型号的电台，看看是不是也有同样的问题。

通过以上3个步骤的排查，基本能确定是在哪里出了问题。

希望能得到您的回复。

73

bg7yoz

**Comment by gnotu** [comment]
@N0BOY everything was fine on 0.88.
Also, 0.89 was fine until recently.

@bg7yoz I will try your suggestions and report back.

73, MIke KK7ER

**Comment by gnotu** [comment]
I tested FT8CN 0.90 on a Google Pixel 6A and a QDX transceiver and it works fine.
I tested FT8CN 0.90 on a Google Pixel 6a and a QMX transceiver and it exhibits the problem.
I tested FT8CN 0.90 on a Samsung Galaxy A03s and a QDX transceiver and it works fine.
I tested FT8CN 0.90 on a Samsung Galaxy A03s and a QMX transceiver and it exhibits the problem.

So...  it looks like a QMX issue.

73, Mike KK7ER

**Comment by bg7yoz** [comment]
抄收了。

如果在使用中遇到具体问题可以及时提交，让我们把ft8cn做得更好。

谢谢！

bg7yoz

**Comment by gnotu** [comment]
@bg7yoz, another comparison is this:  the QMX works fine with WSJT-X on a PC.  There must be something unique about the combination of QMX and FT8CN.

Does FT8CN do any gain adjustment via CAT?  I can try dumping the QMX CAT logs if you think it would help.

Also, I only saw it once, but between first and second transmissions I saw FT8CN display a message about Bluetooth Audio.  Just as I noticed it, it disappeared (so I cannot tell you what it said).  Could FT8CN be switching audio devices between the first and second transmissions?

Thanks!

73, Mike KK7ER

**Comment by bg7yoz** [comment]
hi, Mike

1.FT8CN没有做通过cat调整增益的操作。这也许是手机与pc之间的差异？我之前也发现一些现象：个别手机在播放音频时，前几秒钟声音正常，然后声音会逐渐降低，声音的频率越高，这个现象似乎越明显。这个音频变化不是FT8CN造成的，FT8CN没有自动地对音频强度做改变...是不是手机的某种保护机制？我也不清楚。

2.关于蓝牙。当有蓝牙设备连接到手机，FT8CN都会提示有蓝牙设备接入，如果不是音频设备，您完全不用理会。我认为蓝牙与QMX的问题没有关联性。

以上，也许对您排查问题有帮助。

73

bg7yoz

**Comment by gnotu** [comment]
The designer of the QMX is going to investigate.
https://groups.io/g/QRPLabs/message/108670

73, Mike KK7ER

**Comment by gnotu** [comment]
With FT8CN 0.92 and QMX firmware 1_00_017 this issue has been resolved per my testing.

73, Mike KK7ER

**Comment by sq5jup** [comment]
Had the same issue when I try "OOtB", FT8CN 0.92 + latest QMX firmware.
It start to work on my Mi 9 when switched "Adjust media sound in multiple apps" at Sound assistant configuration.
Hope you can do the same on your mobile.

73 de SQ5J,
Piotr
