### ISSUE TITLE
Direct Transmit message does not work

### ISSUE THREAD

**Issue by PD5DJ** [N0BOY/FT8CN#7]
When a station calls in time window 00/30, and I respond on his cq directly after in time window 15/45. It does not directly Transmits my message.. it waits untile time window 15/45 is over, then goes over to 00/30, and after that back in 15/45 goes to transmit.
This is too late.

I should directly transmit after I hit reply. and partially sends out my message in 15/45. no matter if this time window is already halfway.

**Comment by N0BOY** [comment]
Bjorn, if you start TX within 2 seconds of first 15/45 window, it will transmit immediately. Otherwise, it will wait till next 15/45 cycle.

A tip: "swept left" of the message for quick reply.
