### ISSUE TITLE
please opensource ft8 decoder

### ISSUE THREAD

**Issue by StrideZhou** [N0BOY/FT8CN#70]
we are aim to increase ft8 decode efficience and make the app more powerful please opensource the libft8cn.so or the decode part of it. 
believe in the power of commuity, we will make inprovment

**Comment by d3m3vilurr** [comment]
it could be fork version of the [ft8_lib](https://github.com/kgoba/ft8_lib)

you can find it on old tree; https://github.com/N0BOY/FT8CN/tree/cb1d1284c/ft8CN/app/src/main/cpp
