### ISSUE TITLE
Yaesu FT-991A USB  / DATA-USB incorrect mode settings

### ISSUE THREAD

**Issue by ilyxa** [N0BOY/FT8CN#73]
FT8CN ver 0.90 (checked w/ 0.88 (problem confirmed) /0.87(not sure about version)).

Rig Yaesu FT-991A

Problem: incorrect MODE setting while using FT8CN.

Reproduce:
- rig is powered on, freq is set to 18100, MODE = DATA-USB, width, agc, already set as expected.
- connecting cable to smartphone, run FT8CN - freq still here, MODE changed to USB (here is problem = limited bw and transmission not possible at all) = expected mode DATA-USB (MD0C?)
- change MODE to D-U/DATA-USB manually, freq shifting +70hz, manually correct it on rig = made some some good stuff, CQ and DXing, works perfectly
- ... until I go to Settings to change freq, for example - MODE change again to USB, need to revert it back after completing setup.

Of course, rig already checked and work just fine on WSJT-X setup in field and stationary.

Not a big deal, but sometimes it's a bit annoying especially when forgot to change settings and lost interesting CQ :face_with_spiral_eyes: 

Also this can be my ordinary mistake and some kind of mis-configuration on rig, I'll can get it )

TNX DE UB6LUM

**Comment by bg7yoz** [comment]
hi，UB6LUM

谢谢您反馈的信息，在0.91版本，将按照您的要求修改。电台类型中增加DATA-USB模式。

![WechatIMG2](https://github.com/N0BOY/FT8CN/assets/131873746/06f067a5-7052-4da7-8480-c12b00cddc6b)


谢谢！


BG7YOZ

**Comment by ilyxa** [comment]
Can`t wait )

Thank you!

UB6LUM
