### ISSUE TITLE
Yaesu FT-991A incorrect mode selected / RTTY-USB Selected

### ISSUE THREAD

**Issue by ilyxa** [N0BOY/FT8CN#75]
Ver: 0.91
Rig: YAESU FT-991A
Problem: incorrect mode selected  (RTTY-USB), when selecting Yaesu FT-891/991 (USB or DATA-USB). Mode alwayes to R-U (RTTY-USB).

Rig | YAESU FT-891/991(DATA-USB)
-- | --
Operation mode | CAT
CIV address | 0xA4
Baud rate | 38400
Available serial ports | \0x03EB\0x10C4\0xEA70\0x0\0x03EB\0x10C4\0xEA70\0x1
Instruction Set | YAESU FT-891
Connect mode | USB Cable
Baud rate | 38400
Band | 21.074MHz (15m)
Rig frequency | 21.074MHz

This could be related to #73 ?

I can provide logs (which one), etc per request if you need to.

BTW, frequency jump problem completely solved, tnx :)

TNX de UB6LUM

**Comment by ilyxa** [comment]
Query configuration information:


KeyName | Value
-- | --
callsign | UB6LUM/M
deepMode | 1
ctrMode | 1
synFreq | 0
autoCallFollow | 0
model | 36
instruction | 19
grid | KN97
launchSupervision | 0
pttDelay | 100
baudRate | 38400
noReplyLimit | 6
bandFreq | 21074000
freq | 2289

<br class="Apple-interchange-newline">

**Comment by ilyxa** [comment]
seems that there is an error in app/src/main/java/com/bg7yoz/ft8cn/rigs/Yaesu3RigConstant.java
31:    private static final String USB_MODE_DATA = "MD09;"; 
MD09 <-- RTTY-USB mode, per CAT refrence, this looks like typo.

Also I cant understand when and how MD0C (DATA-USB) selected :(

**Comment by ilyxa** [comment]
Checked:
- set "Yaesu FT-891/991 (USB)" - got behavior  as in <0.90 -  USB mode selected, expected freq (fixed!)
- set "Yaesu FT-891/991 (DATA-USB)" - RTTY-USB mode set (MD09), must be MD0C (if I understand right), freq set as expected

**Comment by ilyxa** [comment]
Yep.

```
app/src/main/java/com/bg7yoz/ft8cn/rigs/Yaesu3RigConstant.java
31: private static final String USB_MODE_DATA = "MD09;";

```
replaced with: 

`private static final String USB_MODE_DATA = "MD0C;";
`
Rebuild, problem solved. Seems like typo.

**Comment by bg7yoz** [comment]
hello, @ilyxa 

很感谢你的反馈。已经按照你的提示，我重新编译了apk，请再次测试一下是否正确。如果正确，我将作为patch 1 发布。

[FT8CN_991_Test_20230913.apk.zip](https://github.com/N0BOY/FT8CN/files/12593937/FT8CN_991_Test_20230913.apk.zip)


期待你的回复。

73

bg7yoz

**Comment by ilyxa** [comment]
Thanks, will check this evening!

谢谢，今晚检查！!

73
UB6LUM

**Comment by ilyxa** [comment]
Problem solved. Thank you very much!

**Comment by ilyxa** [comment]
Solution/workaround provided, @bg7yoz THX de UB6LUM.

73!

**Comment by bg7yoz** [comment]
> Problem solved. Thank you very much!

好的，会以Patch 1 发布，谢谢！

bg7yoz
