### ISSUE TITLE
SWL

### ISSUE THREAD

**Issue by UT8IIV** [N0BOY/FT8CN#8]
Hello, tell me please, in version 0.85 of the program there is already the possibility of saving received callsigns in (adi) for the radio observer? (SWL) Thanks for the reply.

**Comment by PD5DJ** [comment]
Indeed i could not find any export feature too.

**Comment by N0BOY** [comment]
> Hello, tell me please, in version 0.85 of the program there is already the possibility of saving received callsigns in (adi) for the radio observer? (SWL) Thanks for the reply.

@UT8IIV SWL mode has been added to the v0.87 release. Give it a try.
