### ISSUE TITLE
【求助】ft8_lib中kiss_fftr快速傅里叶变换后如何得到码元？

### ISSUE THREAD

**Issue by liuaifu** [N0BOY/FT8CN#82]
国内可能就这里对FT8_lib最熟悉了，看了好长时间，快速傅里叶变换后云里雾里，还用到科斯塔斯环，可否给讲一下kiss_fftr后如何解调得到码元？也欢迎老外帮忙讲解一下。

The person most familiar with FT8_lib in China may be here. After looking at it for a long time, it is foggy after fast Fourier transform, and Costas loop is also used. Can you tell me how to get the channel symbols or FT8 Bits after kiss_fftr? Foreigners are also welcome to help explain.

**Comment by liuaifu** [comment]
基本上搞清楚了。

**Comment by bg7yoz** [comment]
粗略来说，大概有一下几步：
1.快速傅立叶变换，得到频域数据。
2.同步。根据同步符号（开始（0-7）、中间（36-43）、结尾（72-79）科斯塔阵列）确定信号的位置（频率和时间偏移）。
3.基于LDPC解码，做CRC校验，解包。
