### ISSUE TITLE
No source code or license

### ISSUE THREAD

**Issue by rogerclarkmelbourne** [N0BOY/FT8CN#9]
I can't see any source code in this repo.

Is this an Open Source project, ?

**Comment by PD5DJ** [comment]
No open source project.

**Comment by rogerclarkmelbourne** [comment]
OK. It seems risky installing an unknown APK with no source code.

How can I scan this for viruses etc

**Comment by rogerclarkmelbourne** [comment]
FYI. I scanned the latest release using VirusTotal, and it did not report any viruses. However this only scans for know virus engines, it would not detect things like capturing the shared clipboard and sending that data to the cloud etc

I've not installed it, as I don't have an android VM available at the moment, so I don't know what permissions it requests

https://www.virustotal.com/gui/file/3a9b9bcfdc3f68aedded21eddf662137b2fd15f84ac27d3c600e30c50a8a9a55?nocache=1

**Comment by PedroPauloBrazil** [comment]
> FYI. I scanned the latest release using VirusTotal, and it did not report any viruses. However this only scans for know virus engines, it would not detect things like capturing the shared clipboard and sending that data to the cloud etc
> 
> I've not installed it, as I don't have an android VM available at the moment, so I don't know what permissions it requests
> 
> https://www.virustotal.com/gui/file/3a9b9bcfdc3f68aedded21eddf662137b2fd15f84ac27d3c600e30c50a8a9a55?nocache=1

Hello, Roger, long time no see!

I have installed this app on my test device and it not only performs very well but appears to be safe too. It requires only 3 permissions: 1) near devces, 2) localization and 3) microphone. 
The absence of a license, English documentation and source code is not so good as desirable, but anyways the app worth a try.

Regards,

Pedro Paulo - PU2OIP

**Comment by rogerclarkmelbourne** [comment]
Yes. Being of unknown origin is not ideal.

I will put it onto a small tablet which I do use for email or anything which requires login etc. 

I would not put unknown apps onto any devices you also use for banking etc
(I don't use banking apps myself)


BTW.

I did notice there was another paid app in the Playstore for $9.99 for WSPR



I also wonder whether both the paid / closed source app and this app use GPL libraries.

It seems unlikely that they have written the WSPR DSP code from scratch themselves

Perhaps the WSPR DSP libraries they use are MIT or Apache license.  But as neither are open source its impossible to know which libraries they have used

**Comment by PedroPauloBrazil** [comment]
Yes, I do not use "hot" devices to test new apps too (I have a segregated account too for this purpose). BTW, this app is very good and I am using it to make my portable operations, with very good results. Congratulations to the author!

And yes, there are some paid wspr and ft8 apps on the store, but I don't have experimented them.
 73!

**Comment by N0BOY** [comment]
The developer does have the plan to release source code once the app becomes more mature.

This app is still experimental, please report any bug or security concern you may find, to help with the development.

Btw, let me know if anyone is interested in helping with localizing the documentation.

**Comment by rogerclarkmelbourne** [comment]
@N0BOY 

OK. Thanks.

I can't help localisation as I only speak / read / write  English

**Comment by N0BOY** [comment]
Source code released under MIT License

**Comment by rogerclarkmelbourne** [comment]
wow.

Thanks

**Comment by SpudGunMan** [comment]
> wow.
> 
> 
> 
> Thanks

Indeed, I didn't get such kindness when I asked, thanks this was interesting and fun project!. 73

**Comment by ghost** [comment]
To Whom it may concern.  I did a security scan of the apk file with VirusTotal and it flagged it with possible malware. 
https://www.virustotal.com/gui/url/659ce8fab91991be3abdcc3349e0fd9044f59d0a450363d025eab0a382190812

Thanks
